### ISSUE TITLE
Datti fuoco e prova questo

### ISSUE THREAD

**Issue by CoderXYZ7** [TTVTheCats/PatchPulse#1]
```css

/* ===================
   Base Styles
   =================== */
html, body {
  height: 100%;
  margin: 0;
  background-color: #111313;
}

body {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

/* ===================
   Typography
   =================== */
@font-face {
  font-family: 'Vanguard';
  src: url('Fontspring-DEMO-vanguardcf-demibold.otf') format('woff2'),
       url('Fontspring-DEMO-vanguardcf-demibold.otf') format('woff');
}

@font-face {
  font-family: 'RobotoM';
  src: url('Roboto-Medium.ttf') format('woff');
}

h1 {
  font-family: Vanguard;
  font-size: 7vw;
  text-align: center;
  color: white;
}

a {
  font-family: Vanguard;
  font-size: clamp(16px, 5vw, 80px);
  color: white;
  text-decoration: none;
}

a:hover {
  color: #FDBE00;
  text-shadow: rgba(253, 190, 0, 1) 0px 0px 20px;
}

/* ===================
   Layout Components
   =================== */
.content-wrapper {
  flex: 1 0 auto;
}

.flex-container {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-evenly;
  align-items: flex-end;
  gap: 1vw;
  padding: 0;
  margin: 0;
  list-style: none;
}

.flex2-container {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-between;
  padding-left: 2vw;
  padding-right: 2vw;
  gap: 5vh;
}

/* ===================
   Components
   =================== */
.flex-item {
  padding: 4px;
  margin-top: 10px;
  line-height: 150px;
  font-size: 8vw;
  text-align: center;
  font-family: Vanguard;
}

.button-container {
  display: flex;
  flex-direction: row;
  justify-content: center;
  gap: 10vw;
  width: 100%;
}

.button1 {
  border: 3px solid white;
  border-radius: 25px;
  padding: 15px 30px;
  background-color: transparent;
  white-space: nowrap;
  font-size: 4vw;
  line-height: 1.3;
}

.mainIcon {
  width: clamp(16px, 20vw, 400px);
  height: auto;
}

.vwImmageSizeble {
  width: 15vw;
  height: auto;
}

/* ===================
   Form Styles
   =================== */
.form-container {
  width: 50vw;
  height: 370px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  background-color: #171717;
  padding: 20px;
  border-radius: 10px;
  border: 3px solid #ffffff;
  margin: auto;
}

.form1 {
  margin: 10px 0;
  padding: 10px;
  width: 300px;
  background-color: #171717;
  border: 2px solid white;
  color: #ffffff;
  border-radius: 5px;
}

.form1:hover {
  background-color: #353434;
}

input[type="submit"], input[type="checkbox"] {
  background-color: #171717;
  color: white;
  cursor: pointer;
}

input[type="submit"]:hover {
  background-color: #444;
}

/* ===================
   Footer Styles
   =================== */
footer {
  flex-shrink: 0;
  background-color: #0e0e0e;
}

.footer-item {
  font-size: 2vw;
  color: rgb(168, 168, 168);
}

.footr {
  background-color: #0e0e0e;
}

/* ===================
   Utility Classes
   =================== */
.bg {
  color: rgb(29, 29, 29);
}

.qr-container {
  display: none;
}

.p2 {
  text-align: center;
  font-size: 4vh;
  color: rgb(232, 230, 227);
  font-family: 'Vanguard';
  margin: 0;
  padding: 0 20px;
}

.p3 {
  text-align: center;
  font-size: clamp(20px, 0.67vw, 20px);
  color: rgb(232, 230, 227);
  font-family: 'Vanguard';
  margin: 0;
  padding: 0;
}

.p3 a {
  color: rgb(152, 143, 129);
  font-family: 'RobotoM';
  font-size: 14px;
  text-align: center;
}

.fastScan {
  font-size: clamp(10px, 1vw, 40px);
  color: white;
  padding: 4%;
}

/* ===================
   Media Queries
   =================== */
@media all and (max-width: 1251px) {
  h1 {
    font-size: 12vw;
  }

  .mainIcon {
    width: 25vw;
    height: auto;
  }

  .flex2-container {
    flex-direction: column;
    align-items: center;
    gap: 5vh;
    padding: 14vw 0 0;
    margin: auto;
  }

  .flex-container {
    align-items: center;
    justify-content: space-evenly;
    height: 6vh;
  }

  .flex-item {
    font-size: 5vw;
    line-height: 1.9;
  }

  .vwImmageSizeble {
    width: 100%;
    height: 18vw;
    max-height: 20vh;
    object-fit: cover;
  }

  .button1 {
    border-width: 2px;
    font-size: 8vw;
  }

  .footer-item {
    font-size: 4vw;
  }

  .form-container {
    width: 80vw;
    height: auto;
    padding: 2%;
    box-sizing: border-box;
  }

  .form1 {
    padding: 2%;
    width: 90%;
    max-width: 300px;
    height: auto;
    font-size: 2vw;
    box-sizing: border-box;
  }

  .qr-container {
    display: flex;
    justify-content: center;
    margin-top: 4vh;
  }

  .qr-code {
    width: 30vw;
    height: auto;
    max-width: 200px;
  }

  .flex2-itemGrow {
    order: 2;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .flex2-container > img:first-child {
    order: 1;
  }

  .flex2-container > img:last-child {
    order: 3;
  }
}
```
